version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
       - .development.env
    volumes:
      - .:/app
    ports:
      - 8082:8082
    depends_on:
      - postgres
    restart: always   

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: "online-store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "13254687901"
    ports:
      - 5432:5432
    volumes:
     - pgdata:/var/lib/postresql/data
    restart: always

volumes:
  pgdata:

  